### ISSUE TITLE
upload an image 

### ISSUE THREAD

**Issue by nouhailahanbali** [hadikachmar3/grocery_admin_panel_course#1]
i get a problem when i choose an image in new product i got an error it won't show on list product like a big red  x on the image

**Comment by nouhailahanbali** [comment]
![updateproduct](https://user-images.githubusercontent.com/86674588/187033864-ccbf8200-bc93-4b89-9f8f-89a0f3f95a9a.png)

**Comment by hadikachmar3** [comment]
Hello,

The error is not clear.
You can also use the attached code for the lecture resources, or compare it to your code. It should fix the issue, i believe that it can be fixed easily.

**Comment by nouhailahanbali** [comment]
the problem is the imagenetwork that what show on debug console .

**Comment by nouhailahanbali** [comment]
and i used your project it self and that the error i get .

**Comment by hadikachmar3** [comment]
Did u watch Lecture 46? Where I explained how to run flutter web app?

For any further questions I recommend you to use discord or ask in the Q&A section on Udemy
